#include <sys/syscall.h>
#include "syscalls.h"

static const syscall_info syscall_table[] = {
  [SYS_read]           = { "read",  {SATYPE_SIGNED, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_write]          = { "write", {SATYPE_SIGNED, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_open]           = { "open",  {SATYPE_STRING, SATYPE_FLAGS, SATYPE_OCT} },
  [SYS_close]          = { "close", {SATYPE_SIGNED} },
  [SYS_stat]           = { "stat",  {SATYPE_STRING, SATYPE_HEX} }, 
  [SYS_fstat]          = { "fstat", {SATYPE_SIGNED, SATYPE_HEX} },
  [SYS_lstat]          = { "lstat", {SATYPE_STRING, SATYPE_HEX} },
  [SYS_poll]           = { "poll",  {SATYPE_HEX, SATYPE_UNSIGNED, SATYPE_SIGNED} },
  [SYS_lseek]          = { "lseek", {SATYPE_SIGNED, SATYPE_SIGNED64, SATYPE_UNSIGNED} },
  [SYS_mmap]           = { "mmap",  {SATYPE_HEX, SATYPE_UNSIGNED, SATYPE_FLAGS, SATYPE_FLAGS, SATYPE_SIGNED, SATYPE_UNSIGNED} },
  [SYS_ioctl]          = { "ioctl",  {SATYPE_SIGNED, SATYPE_HEX, SATYPE_HEX} },
  [SYS_access]         = { "access",  {SATYPE_STRING, SATYPE_FLAGS} },
  [SYS_shmget]         = { "shmget",  {SATYPE_HEX, SATYPE_UNSIGNED, SATYPE_FLAGS} },
  [SYS_shmat]          = { "shmat",   {SATYPE_SIGNED, SATYPE_HEX, SATYPE_FLAGS} },
  [SYS_shmctl]         = { "shmctl",  {SATYPE_SIGNED, SATYPE_SIGNED, SATYPE_HEX} },
  [SYS_dup]            = { "dup",     {SATYPE_SIGNED} },
  [SYS_dup2]           = { "dup2",    {SATYPE_SIGNED, SATYPE_SIGNED} },
  [SYS_pause]          = { "pause",   {SATYPE_NONE} },
  [SYS_nanosleep]      = { "nanosleep",  {SATYPE_HEX, SATYPE_HEX} },
  [SYS_alarm]          = { "alarm",      {SATYPE_UNSIGNED} },
  [SYS_getpid]         = { "getpid",     {SATYPE_NONE} },
  [SYS_sendfile]       = { "sendfile",   {SATYPE_SIGNED, SATYPE_SIGNED, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_socket]         = { "socket",  {SATYPE_SIGNED, SATYPE_SIGNED, SATYPE_SIGNED} },
  [SYS_connect]        = { "connect", {SATYPE_SIGNED, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_accept]         = { "accept",{SATYPE_SIGNED, SATYPE_HEX, SATYPE_HEX} },
  [SYS_sendto]         = { "sendto",   {SATYPE_SIGNED, SATYPE_HEX, SATYPE_UNSIGNED, SATYPE_FLAGS, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_recvfrom]       = { "recvfrom",  {SATYPE_SIGNED, SATYPE_HEX, SATYPE_UNSIGNED, SATYPE_FLAGS, SATYPE_HEX, SATYPE_HEX} },
  [SYS_shutdown]       = { "shutdown",  {SATYPE_SIGNED, SATYPE_SIGNED} },
  [SYS_bind]           = { "bind",   {SATYPE_SIGNED, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_listen]         = { "listen", {SATYPE_SIGNED, SATYPE_SIGNED} },
  [SYS_clone]          = { "clone",  {SATYPE_FLAGS, SATYPE_HEX, SATYPE_HEX, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_fork]           = { "fork",   {SATYPE_NONE} },
  [SYS_execve]         = { "execve", {SATYPE_STRING, SATYPE_HEX, SATYPE_HEX} },
  [SYS_exit]           = { "exit",   {SATYPE_SIGNED} },
  [SYS_wait4]          = { "wait4",  {SATYPE_SIGNED, SATYPE_HEX, SATYPE_FLAGS, SATYPE_HEX} },
  [SYS_kill]           = { "kill",   {SATYPE_SIGNED, SATYPE_SIGNED} },
  [SYS_uname]          = { "uname",  {SATYPE_HEX} },
  [SYS_fcntl]          = { "fcntl",  {SATYPE_SIGNED, SATYPE_UNSIGNED, SATYPE_UNSIGNED} },
  [SYS_getcwd]         = { "getcwd", {SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_chdir]          = { "chdir",  {SATYPE_STRING} },
  [SYS_rename]         = { "rename", {SATYPE_STRING, SATYPE_STRING} },
  [SYS_mkdir]          = { "mkdir",  {SATYPE_STRING, SATYPE_OCT} },
  [SYS_rmdir]          = { "rmdir",  {SATYPE_STRING} },
  [SYS_creat]          = { "creat",  {SATYPE_STRING, SATYPE_OCT} },
  [SYS_link]           = { "link",   {SATYPE_STRING, SATYPE_STRING} },
  [SYS_unlink]         = { "unlink", {SATYPE_STRING} },
  [SYS_ptrace]         = { "ptrace", {SATYPE_SIGNED, SATYPE_SIGNED, SATYPE_HEX, SATYPE_HEX} },
  [SYS_getuid]         = { "getuid", {SATYPE_NONE} },
  [SYS_getgid]         = { "getgid", {SATYPE_NONE} },
  [SYS_setuid]         = { "setuid", {SATYPE_UNSIGNED} },
  [SYS_setgid]         = { "setgid", {SATYPE_UNSIGNED} },
  [SYS_openat]         = { "openat", {SATYPE_SIGNED, SATYPE_STRING, SATYPE_FLAGS, SATYPE_OCT} },
  [SYS_brk]            = { "brk",    {SATYPE_HEX} },
  [SYS_mprotect]       = { "mprotect",   {SATYPE_HEX, SATYPE_UNSIGNED, SATYPE_FLAGS} },
  [SYS_munmap]         = { "munmap",     {SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_getrandom]      = { "getrandom",  {SATYPE_HEX, SATYPE_UNSIGNED, SATYPE_FLAGS} },
  [SYS_prlimit64]      = { "prlimit64",  {SATYPE_SIGNED, SATYPE_UNSIGNED, SATYPE_HEX, SATYPE_HEX} },
  [SYS_pread64]        = { "pread64",    {SATYPE_UNSIGNED, SATYPE_HEX, SATYPE_UNSIGNED, SATYPE_SIGNED64} },
  [SYS_readv]          = { "readv",      {SATYPE_UNSIGNED, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_writev]         = { "writev",     {SATYPE_UNSIGNED, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_pipe]           = { "pipe",    {SATYPE_HEX} },
  [SYS_pipe2]          = { "pipe2",   {SATYPE_HEX, SATYPE_FLAGS} },
  [SYS_select]         = { "select",     {SATYPE_SIGNED, SATYPE_HEX, SATYPE_HEX, SATYPE_HEX, SATYPE_HEX} },
  [SYS_epoll_create1]  = { "epoll_create1",  {SATYPE_FLAGS} },
  [SYS_epoll_wait]     = { "epoll_wait",     {SATYPE_SIGNED, SATYPE_HEX, SATYPE_SIGNED, SATYPE_SIGNED} },
  [SYS_futex]          = { "futex", {SATYPE_HEX, SATYPE_SIGNED, SATYPE_UNSIGNED, SATYPE_HEX, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_getppid]        = { "getppid", {SATYPE_NONE} },
  [SYS_gettid]         = { "gettid", {SATYPE_NONE} },
  [SYS_clock_gettime]  = { "clock_gettime", {SATYPE_HEX, SATYPE_HEX} },
  [SYS_rt_sigaction]   = { "rt_sigaction",  {SATYPE_SIGNED, SATYPE_HEX, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_rt_sigprocmask] = { "rt_sigprocmask",  {SATYPE_SIGNED, SATYPE_HEX, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_rt_sigreturn]   = { "rt_sigreturn",    {SATYPE_NONE} },
  [SYS_arch_prctl]     = { "arch_prctl",      {SATYPE_HEX, SATYPE_HEX} },
  [SYS_newfstatat]     = { "newfstatat",      {SATYPE_SIGNED, SATYPE_STRING, SATYPE_HEX, SATYPE_FLAGS} },
  [SYS_fchdir]         = { "fchdir",          {SATYPE_UNSIGNED} },
  [SYS_faccessat]      = { "faccessat",  {SATYPE_SIGNED, SATYPE_STRING, SATYPE_FLAGS} },
  [SYS_readlink]       = { "readlink",   {SATYPE_STRING, SATYPE_HEX, SATYPE_UNSIGNED} },
  [SYS_readlinkat]     = { "readlinkat", {SATYPE_SIGNED, SATYPE_STRING, SATYPE_HEX, SATYPE_SIGNED} },
  [SYS_exit_group]     = { "exit_group", {SATYPE_SIGNED} },
  [SYS_sigaltstack]     = { "sigaltstack", {SATYPE_HEX, SATYPE_HEX} },
  [SYS_geteuid]     = { "sigaltstack", {SATYPE_NONE} },
  [SYS_getegid]     = { "sigaltstack", {SATYPE_NONE} },
  [SYS_prctl]     = { "prctl", {SATYPE_SIGNED, SATYPE_HEX, SATYPE_HEX, SATYPE_HEX, SATYPE_HEX} },
  [SYS_statx]     = { "statx", {SATYPE_SIGNED, SATYPE_STRING, SATYPE_FLAGS, SATYPE_HEX, SATYPE_HEX} },
};

static const size_t syscall_table_size = sizeof(syscall_table) / sizeof(syscall_table[0]);

const syscall_info *syscall_lookup(long nr) {
  if(nr < 0 || (size_t)nr >= syscall_table_size)
    return NULL;
  const syscall_info *si = &syscall_table[nr];
  return si->name == NULL ? NULL : si;
}
